### ISSUE TITLE
buid.Stop();   ClientProtocolException cannot be cast to  HttpResponseException

### ISSUE THREAD

**Issue by hoysoft** [jenkinsci/java-client-api#118]
public String Stop() throws HttpResponseException, IOException{
        try {
            return client.get(url + "stop");
        }
        catch (IOException ex){
            if(((HttpResponseException)ex).getStatusCode() == 405)
            {
                stopPost();
                return "";
            }
        }
        return "";
    }

 java.lang.ClassCastException: org.apache.http.client.ClientProtocolException cannot be cast to org.apache.http.client.HttpResponseException

**Comment by soninob** [comment]
@hoysoft - how did you manage to get CCE?

**Comment by khmarbaise** [comment]
I would be interested as well...

**Comment by khmarbaise** [comment]
Unfortunately no feedback.

**Comment by hujiachun** [comment]
this bug  still exist
version 0.3.8

<img width="1458" alt="2019-01-07 2 57 15" src="https://user-images.githubusercontent.com/17762932/50753451-e6e50180-128c-11e9-97b7-9cb3b71756bf.png">
