### ISSUE TITLE
Extracting TestReport informations for a build.

### ISSUE THREAD

**Issue by rhehl** [jenkinsci/java-client-api#129]
Hi, 
with https://github.com/RisingOak/jenkins-client/issues/89 there was a way to extract TestReports/TestSuits from ChildReports, would it be possible to add this also to a "normal" non childreport?

as example "mavenJob.details().getLastCompletedBuild().getTestReport().getResult().getSuites()"

greetings

**Comment by khmarbaise** [comment]
Maybe i misunderstand your wish...what do you mean by non childreport ? The test report is related to the build with a particular number ? Or are you thinking about an aggregation over different builds ?

**Comment by khmarbaise** [comment]
Unfortunately no feedback.
