### ISSUE TITLE
Breaking API Change in 1.638?

### ISSUE THREAD

**Issue by mcqueenorama** [jenkinsci/java-client-api#131]
I'm seeing api calls throwing 500s  starting at 1.638, which is a patch to implement security fixes:

https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-11-11

Has anybody else tried this out yet?

I'm doing job creation in a Jenkins unit test:

JenkinsServer jenkins = new JenkinsServer(j.getURL().toURI());

String job11Xml = Resources.toString(Resources.getResource("updated_" + JOB1_CONFIG), Charsets.UTF_8);

jenkins.updateJob(JOB1_NAME, job11Xml);

**Comment by pnathan** [comment]
Sorry to be anal, but can you provide a 'working minimal example'? Maybe a compilable `example.java`?, along with a specification of your Jenkins configuration showing the configuration options you've gotten set up that demonstrate this change?

**Comment by mcqueenorama** [comment]
Yea I know, its a totally lame bug report.  You're not being anal.  I'll get some more data or close this down myself.
