### ISSUE TITLE
Get Credential ID for config.xml

### ISSUE THREAD

**Issue by yongwoohan** [jenkinsci/java-client-api#142]
Define an immediate need to Git username and password in config.xml, must get a Credential ID
How can do a Credential ID?

**Comment by khmarbaise** [comment]
Can you explain what you like to achieve? Would you like to have a credentials ID in your config.xml ?

**Comment by yongwoohan** [comment]
Yes, I would like to hava a credentials ID in Git Server with username and password
first, Define Not credentials default config.xml to start, so To Jenkins-Client Set up to Git server then Be relevant Credentials ID By username and password

**Comment by khmarbaise** [comment]
Credentials ID means there is no user name nor the password in the config.xml. May be you can elaborate more what you like to achieve...

**Comment by yongwoohan** [comment]
![image](https://cloud.githubusercontent.com/assets/18041107/14203143/18ca1dfc-f837-11e5-896d-76199101925d.png)

So, define credentials ID in config.xml

**Comment by khmarbaise** [comment]
You can get the config.xml via JenkinsServer.getJobXml('JobName') where you can extract the credentialsId...from it...
