### ISSUE TITLE
I can't access the /crumbIssuer

### ISSUE THREAD

**Issue by 278668433** [jenkinsci/java-client-api#145]
when i create a job , The program runs to   
           Crumb crumb = getQuietly("/crumbIssuer", Crumb.class);
Will throw out exception : 
            org.apache.http.client.HttpResponseException: Not Found
What needs to be loaded If I want to be successful access   /crumbIssuer

**Comment by khmarbaise** [comment]
Can give detailed information about Jenkins version you are using, what you have tried best would be having a code example ...

**Comment by khmarbaise** [comment]
Unfortunately no feedback.
