### ISSUE TITLE
org.apache.http.client.HttpResponseException: Not Found

### ISSUE THREAD

**Issue by yongwoohan** [jenkinsci/java-client-api#156]
Execute about HttpReponseValidator both "mavenJob.getBuilds().get(index).getTestReport()" and "mavenJob.getBuilds().get(index).getMavenModule()"

"mavenJob" is JenkinsServer.getMavenJob(jobName)
Why did same to error?
Please ReSolution

![image](https://cloud.githubusercontent.com/assets/18041107/14950984/d1f99174-1090-11e6-9200-c4e23e137aef.png)

**Comment by khmarbaise** [comment]
Please check the new released version 0.3.4 if this error is fixed or not...

**Comment by yongwoohan** [comment]
Try to new released version 0.3.5. but to occur about same to error....

**Comment by wangyuesong0** [comment]
It seems that job.getUrl() always return the url starts with http://127.0.0.1:8080/.... which is clearly not the url when i create JenkinsServer object. So for sure the response is 404. Not sure what's happening. Is it fixed?

**Comment by smallmiro** [comment]
I have same problem. 
My project's code is 
```java
JenkinsServer jenkins = new JenkinsServer(new URI("http://localhost:2900/server/"), "user", "password");
Map<String, Job> jobs = jenkins.getJobs();
Job job = jobs.get("jobName");
```
I think there seems to be 'http://localhost:2900/server/job/jobName/'. But result of `job.getUrl()` code is `http://localhost:2900/job/jobName/`.

**Comment by khmarbaise** [comment]
@smallmiro I have tested with the following manual test:

``` java
public class ManualTest {

    private JenkinsServer server;

    @Before
    public void SetUp() throws URISyntaxException {
        server = new JenkinsServer(new URI("http://192.168.0.202:10090/buildserver/"), "admin", "admin");
    }

    @Test
    public void testFolderPluginAPIs() throws Exception {
	Map<String, Job> jobs = server.getJobs();

	for (Entry<String, Job> item : jobs.entrySet()) {
	    System.out.println("Item: " + item.getKey());
	    
	    System.out.println(" -> v:" + item.getValue());
	    Job value = item.getValue();
	    System.out.println(" -> Name:" + value.getName());
	    System.out.println(" -> URL: " + value.getUrl());
	}

    }
}
```
which results in this:
``` 
Item: test
 -> v:com.offbytwo.jenkins.model.Job@94202a9f
 -> Name:test
 -> URL: http://192.168.0.202:10090/buildserver/job/test/
```
Did you get the `org.apache.http.client.HttpResponseException` ? Or was your problem related to the URL ?
