### ISSUE TITLE
JenkinsHttpClient throwing stacktrace to System.out

### ISSUE THREAD

**Issue by jfisbein** [jenkinsci/java-client-api#161]
[JenkinsHttpClient.java#L211](https://github.com/RisingOak/jenkins-client/blob/master/jenkins-client/src/main/java/com/offbytwo/jenkins/client/JenkinsHttpClient.java#L211) is executing `e.printStackTrace()` on exception.
Probably it should use a logger or nothing at all.
The method is called `getQuietly` and is not as quiet as expected :-/

**Comment by khmarbaise** [comment]
Yes take a look at #113
