### ISSUE TITLE
NullPointerException at "BuildCause.getUpstreamBuild()"

### ISSUE THREAD

**Issue by pavelbely** [jenkinsci/java-client-api#172]
This is issue #125 revisited

```
public class BuildCause {
   ...
    private Integer upstreamBuild;
   ...
    public BuildCause() {
        this.upstreamBuild = new Integer(0);
    }

    public int getUpstreamBuild() {
        return upstreamBuild;
    }

    public void setUpstreamBuild(Integer upstreamBuild) {
        this.upstreamBuild = upstreamBuild;
    }
```

NullPointerException is thrown when getUpstreamBuild() is called. 
Probably setting it to default value in the constructor has no effect, as it is being rewritten afterwards.

We use jenkins-client ver. 0.3.5 and Jenkins ver. 1.639

**Comment by khmarbaise** [comment]
First thanks for your check. I have found the real issue which is caused by the BuildWithDetails class which initialised in its method getCauses() the BuildCause but simply overwrote the initialised values which could cause a NPE.
