### ISSUE TITLE
Unable to retrieve down stream jobs build information or names

### ISSUE THREAD

**Issue by upendran** [jenkinsci/java-client-api#175]
I am trying to fetch the information of the sub projects of a job is Jenkins. 

List<Job> joba = job.getDownstreamProjects();

This always returns null even if I have downstream projects. Could you please advice.

                <dependency>
 		  	<groupId>com.offbytwo.jenkins</groupId>
		  	<artifactId>jenkins-client</artifactId>
		  	<version>0.3.5</version>
		</dependency>

My pom.xml has the above dependency.

My Jenkins core is 1.564

**Comment by khmarbaise** [comment]
Do you have the chance to test the current master ?

**Comment by khmarbaise** [comment]
Could you please check the Release 0.3.6?
