### ISSUE TITLE
How do I build time is calculated?

### ISSUE THREAD

**Issue by hanyongwoo** [jenkinsci/java-client-api#178]
I'd has between build start time and end time during build implement
how do I build time?

**Comment by khmarbaise** [comment]
You can get the duration of a build via:
``` java
 JobWithDetails job = JenkinsServer.getJob("XXX");
 BuildWithDetails details = getLastBuild().details();
 System.out.println ("Duration: " + details.getDuration());
```

**Comment by hanyongwoo** [comment]
I got it.
but, I get the build time during building start and end.

**Comment by khmarbaise** [comment]
Maybe I misunderstand you but the duration if the is the time between build start time and build end time ? or to be more accurate:
```
endTime - startTime
```
?
