### ISSUE TITLE
MavenBuild and Build

### ISSUE THREAD

**Issue by tom-smalls** [jenkinsci/java-client-api#179]
This is more of a question than anything else. Why are there separate MavenJob and Job, with MavenBuild and Build objects? The reason I ask is that I was wanting to access the TestReport for the last build of one of our jobs but noticed it is only available through a MavenBuild.

We don't use Maven but produce test reports for our jobs that run builds, and as far as I am aware TestReport is not a Maven concept, so it feels strange that TestReport is only available in MavenBuild.

**Comment by khmarbaise** [comment]
The reason is simple cause someone (me) has implemented it like this never needed something different but of course it makes sense to have a more general solution for this...so this is a feature request...which is useful and improves the API into a more general way...

**Comment by khmarbaise** [comment]
Fixed by #180
