### ISSUE TITLE
How can I get build result status

### ISSUE THREAD

**Issue by melodywin** [jenkinsci/java-client-api#183]
I want to know the Job after the completion of the building, how to get the Job after the build status？

**Comment by khmarbaise** [comment]
Can you more in detail describe what you like to do? To be honest I don't understand your question?

**Comment by melodywin** [comment]
Sorry, My English is poor, I have found the solution to this problem. Thanks~

**Comment by melodywin** [comment]
But I have another question,I want to get the current user name login Jenkins, do you have any method?

**Comment by khmarbaise** [comment]
No there is no such method in the API because if you need a users to access it you have the user name?
