### ISSUE TITLE
org.apache.http.client.HttpResponseException: Not Found (it is back)

### ISSUE THREAD

**Issue by cshupp1** [jenkinsci/java-client-api#189]
This issue may be similar to:
https://github.com/jenkinsci/java-client-api/issues/136

I am using 0.3.4 of the client libraries against Jenkins ver. 2.7.4 with https.

Suppose I do the following (JRuby, but you should be able to follow):

```
xml = args.shift
jenkins_url = args.shift
jenkins_user = args.shift
jenkins_password = args.shift
jenkins = JenkinsServer.new(java.net.URI.new(jenkins_url), jenkins_user, jenkins_password) #call works
jenkins.createJob(name, xml, false) #call works, I see my job created in Jenkins
job = jenkins.getJob(name.strip)
job.build(false) #call fails
```

the call to build yields:

```
[ERROR][2016-09-20T13:58:10][/app/apache-tomcat-8.0.33/webapps/rails_prisme/WEB-INF/app/jobs/jenkins_start_build_job.rb][38] Jenkins Client libraries threw an exception! Not Found
[ERROR][2016-09-20T13:58:10][/app/apache-tomcat-8.0.33/webapps/rails_prisme/WEB-INF/app/jobs/jenkins_start_build_job.rb][39] com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(com/offbytwo/jenkins/client/validator/HttpResponseValidator.java:11)
com.offbytwo.jenkins.client.JenkinsHttpClient.post(com/offbytwo/jenkins/client/JenkinsHttpClient.java:265)
com.offbytwo.jenkins.client.JenkinsHttpClient.post(com/offbytwo/jenkins/client/JenkinsHttpClient.java:438)
com.offbytwo.jenkins.model.Job.build(com/offbytwo/jenkins/model/Job.java:75)
```

Changing the crumb to true doesn't help:
```
ERROR][2016-09-20T17:56:21][/app/apache-tomcat-8.0.33/webapps/rails_prisme/WEB-INF/app/jobs/jenkins_start_build_job.rb][31] About to build true on the crumby thing!
[ERROR][2016-09-20T17:56:21][/app/apache-tomcat-8.0.33/webapps/rails_prisme/WEB-INF/app/jobs/jenkins_start_build_job.rb][39] Jenkins Client libraries threw an exception! Not Found
[ERROR][2016-09-20T17:56:21][/app/apache-tomcat-8.0.33/webapps/rails_prisme/WEB-INF/app/jobs/jenkins_start_build_job.rb][40] com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(com/offbytwo/jenkins/client/validator/HttpResponseValidator.java:11)
com.offbytwo.jenkins.client.JenkinsHttpClient.post(com/offbytwo/jenkins/client/JenkinsHttpClient.java:265)
com.offbytwo.jenkins.client.JenkinsHttpClient.post(com/offbytwo/jenkins/client/JenkinsHttpClient.java:438)
com.offbytwo.jenkins.model.Job.build(com/offbytwo/jenkins/model/Job.java:75)
```

Any ideas?

Thanks,

Cris

**Comment by khmarbaise** [comment]
Would you please check with the newest release 0.3.6...and see if the same issue occurs?

**Comment by cshupp1** [comment]
I am in worse shape with 0.3.6
Now I die with the Not found exception here:
jenkins.createJob(name, xml, false) #call works (on 0.3.4 not 0.3.6), I see my job created in Jenkins

Cris

**Comment by cshupp1** [comment]
Sorry, I stand corrected, no change.  the create job does work.  Someone checked in the wrong url in our seeds file.  I will have him executed!

Still failing during build.

Cris

**Comment by cshupp1** [comment]
OK I replaced job.build with the following:

```
conn = java.net.URL.new("#{jenkins_url}/job/#{name.strip}/build?delay=0sec").openConnection
userpass = "#{jenkins_user}:#{jenkins_password}".to_java
basicAuth = "Basic " + javax.xml.bind.DatatypeConverter.printBase64Binary(userpass.getBytes)
conn.setRequestProperty("Authorization",basicAuth)
conn.setRequestMethod('POST')
conn.getInputStream
```

And jenkins kick off the build, later I do the following:

```
jenkins = JenkinsServer.new(java.net.URI.new(jenkins_config[:url]), jenkins_config[:user],jenkins_config[:password])
jenkins_job = jenkins.getJob(name.strip)
build = jenkins_job.getLastBuild()
details = build.details #bombs out with 'Not Found'
```

Any ideas?

Thanks,

Cris

**Comment by cshupp1** [comment]
![image](https://cloud.githubusercontent.com/assets/5719570/18854839/30d5f3be-841c-11e6-8729-49cfd3356620.png)


Above during the creation of the job we can see we have the context for jenkins.

![image](https://cloud.githubusercontent.com/assets/5719570/18854854/4df910ca-841c-11e6-941d-a163a7a199a2.png)


By the time we build the job the context is lost hence, the 'not found'.

I will continue to debug tomorrow...

Cris

**Comment by cshupp1** [comment]
While debugging your source, I got the clue I finally needed...

I had the debugger leak me a url for building a job with details:

https://vaauscttdbs81.aac.va.gov:8080/jenkins/job/PRISME_loinc-src-data-tech-preview_2016_09_27T17_11_53/api/json

The json was:
'''
{"_class":"hudson.maven.MavenModuleSet","actions":[{"_class":"com.cloudbees.plugins.credentials.ViewCredentialsAction"}],"description":"","displayName":"PRISME_loinc-src-data-tech-preview_2016_09_27T17_11_53","displayNameOrNull":null,"name":"PRISME_loinc-src-data-tech-preview_2016_09_27T17_11_53","url":"https://dev2:8080/job/PRISME_loinc-src-data-tech-preview_2016_09_27T17_11_53/","buildable":true,"builds":[],"color":"notbuilt","firstBuild":null,"healthReport":[],"inQueue":false,"keepDependencies":false,"lastBuild":null,"lastCompletedBuild":null,"lastFailedBuild":null,"lastStableBuild":null,"lastSuccessfulBuild":null,"lastUnstableBuild":null,"lastUnsuccessfulBuild":null,"nextBuildNumber":1,"property":[{"_class":"jenkins.model.BuildDiscarderProperty"}],"queueItem":null,"concurrentBuild":false,"downstreamProjects":[],"scm":{"_class":"hudson.plugins.git.GitSCM"},"upstreamProjects":[],"modules":[]}
'''

Notice the embedded URL:

https://dev2:8080/job/PRISME_loinc-src-data-tech-preview_2016_09_27T17_11_53/

it is garbage...

We are using Jenkins with a proxy server and our jenkins url was badly mis-configured, causing jenkins to give bad urls.

You will find it: Manage Jenkins -> Configure System -> Jenkins URL

I hope this helps someone else...

The penalty for a sys admin mis-configuring is death right?
