### ISSUE TITLE
can i get the jenkins configuration by jenkins api?

### ISSUE THREAD

**Issue by 278668433** [jenkinsci/java-client-api#190]
if yes , how can i get the jenkins configuration?

**Comment by khmarbaise** [comment]
At the moment there is not such function for that...but it might be a useful enhancement of the API...

**Comment by 278668433** [comment]
OK,thank you

**Comment by khmarbaise** [comment]
Sorry I have oversight that there is already an option to get the configuration via:

```java
JenkinsServer.getJobXml("JobName");
````
This will return the `config.xml` as a String.
