### ISSUE TITLE
Jobs list for views within a view is empty

### ISSUE THREAD

**Issue by bpotere** [jenkinsci/java-client-api#196]
Views inside of views do not seem to have their own lists of views and jobs.  Using the following to get views within a view:

```
View allProjectView = server.getView(PROJECT_AREAS);
List<View> allViews = allProjectView.getViews();
```

Debugging while calling getJobDetails on one of these views shows that the list of jobs (jobDetails) is just an empty list at every step, before and after calling this method:

```
List<Job> jobs = projectView.getJobs();
```

Am I missing something or is this a bug?  Is there another way to get the job list?

Using Jenkins 1.58 with version 0.3.6.  We will be updating to 2.0 soon, is this an issue in that version?

**Comment by khmarbaise** [comment]
I have checked with the current master via the [integration tests ](https://github.com/jenkinsci/java-client-api/blob/master/jenkins-client-it-docker/src/test/java/com/offbytwo/jenkins/integration/NoExecutorStartedGetViewIT.java) and checked with an 2.19.2 instance and getting correct results..Do you have a chance to test the current state on master ?

**Comment by bpotere** [comment]
Please close.  I found out later that what looked like views within that PROJECT_AREAS view are actually folders (the server is using the Cloudbees Folders plugin).

**Comment by khmarbaise** [comment]
Ok. Fine. Thanks for the feedback.
