### ISSUE TITLE
The method Job.build(Map<String, String> params) should return queue reference

### ISSUE THREAD

**Issue by igorbljahhin** [jenkinsci/java-client-api#208]
This method https://github.com/jenkinsci/java-client-api/blob/master/jenkins-client/src/main/java/com/offbytwo/jenkins/model/Job.java#L90 should return QueueReference as the method with "boolean crumbFlag" does.

I could make pull request for this change.

**Comment by khmarbaise** [comment]
Would be great if you could make a PR for this...

**Comment by khmarbaise** [comment]
So this has been solved with #104
