### ISSUE TITLE
TestReport method getTotalCount returns 0 everytime

### ISSUE THREAD

**Issue by simjeet** [jenkinsci/java-client-api#212]
TestReport class method getTotalCount always returns 0. I have tried different jobs still the result is 0.

**Comment by khmarbaise** [comment]
It would be helpful having the information about the Jenkins version you are using? Furthermore what kind of Job do you use? freestyle, Maven, etc. ? And furthermore which code you have used to extract the information?

**Comment by simjeet** [comment]
Jenkins Version is 2.3. I am using freestyle job. Using version 3.6 of api.

**Comment by khmarbaise** [comment]
See #184
