### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by matzew** [jenkinsci/java-client-api#216]
Hi,

do you guys have a nightly build, where SNAPSHOT dependencies are published too ?

**Comment by khmarbaise** [comment]
At the moment not...But I can deploy a snapshot state if you like?

**Comment by khmarbaise** [comment]
I have deployed an SNAPSHOT at https://oss.sonatype.org/content/repositories/snapshots/com/offbytwo/jenkins/

**Comment by matzew** [comment]
Danke!

**Comment by khmarbaise** [comment]
Gerne ;-)
