### ISSUE TITLE
Unable to pull logs while build still in progress

### ISSUE THREAD

**Issue by wtrocki** [jenkinsci/java-client-api#217]
What's the preferred way to fetch logs periodically from jenkins?
Most of the clients using response headers to determine if log is complete.

**Example here:** 
https://github.com/silas/node-jenkins/blob/master/lib/build.js#L190

Thanks to that approach logs can be fetched partially. Jenkins also offers another API to retrieve logs using offset. 

**Java client using simplified endpoint:**
https://github.com/jenkinsci/java-client-api/blob/28d9dbf31241a7b7453488f06408b19c387538b2/jenkins-client/src/main/java/com/offbytwo/jenkins/model/BuildWithDetails.java#L358

I would be happy to contribute and build more sophisticated way to retrieve logs, but I just want to know general target for this client, before doing it.

**Comment by matzew** [comment]
:+1:

**Comment by khmarbaise** [comment]
It would be great to offer more ways to fetch logs or better if those can be fetched partially for the users of the API..If you like to contribute that would be great idea...

**Comment by wtrocki** [comment]
Awesome. I think we can do this in many ways some propositions bellow. I would create PR soon.

h4. Fetching logs asynchronously. 
```
BuildWithDetails build=...
build.poolLogs(new LogUpdateListener(){
  function String onData(){...}
  function String onFinish(){..}
}
```

h4. Fetching logs with markers and additional metadata. 
```
BuildWithDetails build=...
LogDetails details = build.fetchLogs(...)
details.finished()
details.delta(); // delivers delta
```

h4. Fetching with specifying limit
```
BuildWithDetails build=...
LogDetails details = build.fetchLogs(0,1000) //  start and offset
```

What would be preferred approach?

**Comment by khmarbaise** [comment]
To be honest I have no preferred approach. Start with that one you like most...may be you can offer multiple ways ;-) ?

**Comment by doterme** [comment]
build.details().getConsoleOutputText()？

**Comment by wtrocki** [comment]
@doterme This is for finished builds when you do not need to deal with the partial console log.

**Comment by doterme** [comment]
@wtrocki ,you should get a build number at first,then get the console log in a timer,this is not for finished,it is in real time

**Comment by wtrocki** [comment]
@doterme - Sorry for confusion. In fact I implemented getConsoleOutputText method to resolve this issue. Obviously this ticket is resolved so I'm going to close it. See referenced PR for more details.
