### ISSUE TITLE
Error contacting jenkins using https and self-signed certificate

### ISSUE THREAD

**Issue by ogirardot** [jenkinsci/java-client-api#226]
It does not seem possible to contact jenkins using an HTTPS url and self-signed certificate : 

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by khmarbaise** [comment]
That looks like a problem with your certificate or the trust store or key store or your certificate is wrong...That is not a problem in the lib...
