### ISSUE TITLE
how can i get a job workspace fileList（question）

### ISSUE THREAD

**Issue by 278668433** [jenkinsci/java-client-api#228]
how can i get a job workspace fileNameList
so i can choose download some type file  whitch i want ? tks

**Comment by khmarbaise** [comment]
Questions should be asked in the forum. Apart from that it does not look like there is a possibility to get such information via REST API....

**Comment by khmarbaise** [comment]
It looks like unfortunately I don't any option to implement that in the API...

**Comment by 278668433** [comment]
OK,think you very much
