### ISSUE TITLE
Invalid password/token for user

### ISSUE THREAD

**Issue by apolloTaotao** [jenkinsci/java-client-api#230]
hello,I am a Java development engineer in China. Our project integrates this Jenkins API  and apply for a long time. We are using version 0.3.6.

Here is the error log when  call jenkins  API  and it  frequently appear : 

### org.apache.http.client.HttpResponseException: Invalid password/token for user: evvuseusre
        at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:149)
        at com.offbytwo.jenkins.model.Job.details(Job.java:45)

Coutld you help me find the cause of the problem？My password is right.

From the point of phenomenon, concurrent calling Jenkins api may be the reason, but I'm not sure.

Some suggestions?

**Comment by apolloTaotao** [comment]
error log sometime like this:

### org.apache.http.client.HttpResponseException: Forbidden
        at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
        at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:149)
        at com.offbytwo.jenkins.JenkinsServer.getJob(JenkinsServer.java:275)
        at com.offbytwo.jenkins.JenkinsServer.getJob(JenkinsServer.java:260)

**Comment by khmarbaise** [comment]
First it would be helpful having some code examples which cause those things...Furthermore please take a look update to 0.3.7...

**Comment by apolloTaotao** [comment]
ok,This is my test code（url password username jobname are replaced ）：

@Test
	public void testCurrent() {
		
		try {
			final JenkinsServer jenkins = new JenkinsServer(new URI("url"), "user", "paswrd");

			final CountDownLatch latch = new CountDownLatch(2);
			
			Thread th1 = new Thread(new Runnable() {
				@Override
				public void run() {
					try {
						
						Job job1 = getJob(jenkins, "joburl1");
						
						System.out.println("job2 build success");
					} catch (IOException e) {
						e.printStackTrace();
					}
					latch.countDown();
				}
			});
			
			Thread th2= new Thread(new Runnable() {
				@Override
				public void run() {
					try {
						
						Job job2 = getJob(jenkins, "joburl2");
						
						System.out.println("job2 build success");
					} catch (IOException e) {
						e.printStackTrace();
					}
					
					latch.countDown();
					
				}
			});
			
			th1.start();
			th2.start();
			
			System.out.println("main start success");
			
			latch.await();
			
			System.out.println("main end");
			
		} catch (Exception e) {
			e.printStackTrace();
		}
		
	}
	
	private Job getJob(JenkinsServer jenkins, String str) throws IOException {
		return jenkins.getJob(str);
	}


  two thread call getJob() at the same time, error log will appear like 

### org.apache.http.client.HttpResponseException: Malformed HTTP basic Authorization header
	at com.offbytwo.jenkins.client.validator.HttpResponseValidator.validateResponse(HttpResponseValidator.java:11)
	at com.offbytwo.jenkins.client.JenkinsHttpClient.get(JenkinsHttpClient.java:149)
	at com.offbytwo.jenkins.JenkinsServer.getJob(JenkinsServer.java:275)
	at com.offbytwo.jenkins.JenkinsServer.getJob(JenkinsServer.java:260)


and I try to synchronize api call,like this and it works.
   
   private synchronized Job getJob(JenkinsServer jenkins, String str) throws IOException {
		return jenkins.getJob(str);
	}

   error log disappear.

  so jenkins api dosen't support concurrent calling, how fix it ？if we call jenkins api in different jvm or process, concurrent calling is inevitable.

**Comment by apolloTaotao** [comment]
not only jenkins.getJob(String str) dosen't support councurrent calling, but also job.build(params) 、 job.details() ..  behave like the same —— error log appear.

**Comment by khmarbaise** [comment]
So to understand that correctly the errors you have described at the beginning of the ticket are related to concurrent calling? So this would mean in the first step no problem exist...cause I didn't expect that java-client-api is thread safe...

I would have been surprised if it had been...I didn't expected it...

So on the other hand is that we could take a deeper look into the root causes of the problems that might go into the correct direction that it will become thread safe...

**Comment by wukq** [comment]
@khmarbaise has this problem been solved？  i had same problem，What should I do?

**Comment by apolloTaotao** [comment]
@wukq  the network call between jenkin-api and jenkenServer should be serialized， specifically you need lock or  synchronized your method； solution can be deduced when you try above-mentioned code。  futhermore, if your jenkin-api running in a  distributed environment，  distributed lock (such as zookeeper)  need to be considered

these are my solutions and you can have a try
