### ISSUE TITLE
How can I include crumb in building job request?

### ISSUE THREAD

**Issue by ghost** [jenkinsci/java-client-api#233]
URI uri = new URI(JENKINS_URL);
    		JenkinsHttpClient client = new JenkinsHttpClient(uri, "xxx", "xxx");
    		Crumb crumb = client.getQuietly("/crumbIssuer", Crumb.class);
    		JenkinsServer server = new JenkinsServer(client);
    		Map<String, Job> jobs = server.getJobs();
    		Job job = jobs.get("test");
    		Map<String, String> params = new HashMap<>();
    		job.build(params);

This will through org.apache.http.client.HttpResponseException: No valid crumb was included in the request

**Comment by khmarbaise** [comment]
First if this is not an issue please ask in the [forum](https://groups.google.com/forum/#!forum/java-client-api) apart from that you can call:
```java
    public QueueReference build(Map<String, String> params, boolean crumbFlag);
```
which is part for Java Client API since release 0.3.7..
