### ISSUE TITLE
Job build seems to do nothing

### ISSUE THREAD

**Issue by pmbsa** [jenkinsci/java-client-api#242]
Hi, apologies, I suspect this is simply a case of user being dull but I cant seem to trigger a build for some reason.

I am getting a job back from jenkins without an issue, I can see all its details but for some reason when I execute job.build() the build doesn't trigger. 

I get a QueueReference and if I execute qr.getQueueItemUrlPart() I get a url that is correct. I can past that into a browser and a build will start but the actual build() method on job seems to do nothing for me.

thanks
Paul

**Comment by pmbsa** [comment]
I managed to get addtional information. I suspect its very much related to my jenkins being behind an apache proxy. I am getting 301 errors under the covers

 <p>The document has moved <a href="https://MYIP/jenkins/job/TestBuild/build/api/json">here</a>.</p>[\n]

no idea why that's happening but its entirely possible it has something do with my implementation

**Comment by khmarbaise** [comment]
So I will close this question. If you have furthermore informations please don't hesitate to reopen the issue.
