### ISSUE TITLE
does it support for pipline?

### ISSUE THREAD

**Issue by xiaosazixian** [jenkinsci/java-client-api#246]

**Comment by rjkernick** [comment]
I am also interested in pipeline support. Not looking like it directly supports it though

**Comment by khmarbaise** [comment]
No there is currently no support for it. The question is in which way should it be supported ?

**Comment by rjkernick** [comment]
Just need a top level class that knows how to dive into the details. I can use the api to do it, but have to use nested for loops that are getting folder jobs within folder jobs.
