### ISSUE TITLE
Create a job with sources

### ISSUE THREAD

**Issue by AlecKotovichSAM** [jenkinsci/java-client-api#255]
Hi!

it is possible to create a job with attached sources instead of specifying a folder location for them?

**Comment by khmarbaise** [comment]
What do you mean by attached sources? Can you give an example for this?

**Comment by AlecKotovichSAM** [comment]
I mean, job is created empty by default. It is possible to specify directory only for project sources. Maybe, it is possible to create a job together with project sources via api call? Attach a ZIP with sources or smth else?

**Comment by khmarbaise** [comment]
You can created a job using a `config.xml` ...having a source directory or a zip file of sources is at the moment not possible but it might be a good improvement...What about offering a patch/pull request for this enhancement ?

**Comment by AlecKotovichSAM** [comment]
Thanks!
