### ISSUE TITLE
No valid crumb was included in the request

### ISSUE THREAD

**Issue by aleklukashevich** [jenkinsci/java-client-api#277]
I'm trying to build job by using following code 
`server.getJobs().get("my_job").build()`

but getting follwoing error 

`result = {HttpResponseException@3746} Method threw 'org.apache.http.client.HttpResponseException' exception.
 statusCode = 403
 detailMessage = "No valid crumb was included in the request"
 cause = {HttpResponseException@3746} "org.apache.http.client.HttpResponseException: No valid crumb was included in the request"
 stackTrace = {StackTraceElement[30]@3810} 
 suppressedExceptions = {Collections$UnmodifiableRandomAccessList@3811}  size = 0`

as I understood crumd data is different for logged in and not logged in users. 
So I guess would be cool to set crumb data manually as a parameter to `new JenkinsServer()`

**Comment by aleklukashevich** [comment]
`server.getJob("JOB").updateDescription("test! lal lal lal lalalalal");` - unable to update description because of 403 error, this is the same reason

**Comment by rpionke** [comment]
did you used `public void updateDescription(String description, boolean crumbFlag) throws IOException` already?

**Comment by aleklukashevich** [comment]
Wow! works that way.
Thanks.
