### ISSUE TITLE
(Question) How to provide Crumb information

### ISSUE THREAD

**Issue by jhelbling** [jenkinsci/java-client-api#279]
I believe I understood the "crumb concept", but is it possible to pass it along if using the following code:
	
```
JenkinsHttpClient client = new JenkinsHttpClient(new URI("http://myjenkins:8082"), "xxx", "pass");	
JenkinsServer server = new JenkinsServer(client);
Map<String,Job> jobs = server.getJobs();
JobWithDetails details = jobs.get("myJob").details();
details.build();
```

I'm getting following error (403):

`No valid crumb was included in the request</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>[\n]`

Do you have any hint? Is the easy piece of code above actually wrong?

**Comment by rpionke** [comment]
please look at the following issue: https://github.com/jenkinsci/java-client-api/issues/277

**Comment by jhelbling** [comment]
Cheers, works like a charm now!
