### ISSUE TITLE
Typo in Fix for #172

### ISSUE THREAD

**Issue by tuliren** [jenkinsci/java-client-api#282]
In this [commit](
https://github.com/jenkinsci/java-client-api/commit/a0feba25138cc99ac6917bb407f17434afa8448c), when setting upstream URL, a wrong parameter was checked:
```java
String upstreamUrl = (String) cause.get("upstreamUrl");
if (!Strings.isNullOrEmpty(upstreamProject)) {
    cause_object.setUpstreamUrl(upstreamUrl);
}
```

**Comment by khmarbaise** [comment]
Can you please make a pull request of it so I can merge it ?

**Comment by tuliren** [comment]
@khmarbaise, yes, I have created a PR here: https://github.com/jenkinsci/java-client-api/pull/283

Thanks.
