### ISSUE TITLE
Refactor: Useful utility/helper methods could be refactored into seperate classes

### ISSUE THREAD

**Issue by dellgreen** [jenkinsci/java-client-api#291]
There are several useful  jenkins url manipulation/creation private methods in JenkinsServer and other classes for example:

toJobBaseUrl()
toBaseUrl()
toViewBaseUrl()
api()
urlJoin()
noapi()

It would be nice if these were in public utility classes as some applications may like to create full URIs  without drilling down through multiple calls to the server. It would also reduce the size of the main classes and make unit testing simpler for these methods.

**Comment by khmarbaise** [comment]
Looks great. Can you also add the license header and add yourself as Author in the classfiles and update the ReleaseNotes.md file accordingly

**Comment by khmarbaise** [comment]
Ah...you missed to add:
```
Fixed #XX
```

in the commit message..So I close the issue manually...

**Comment by dellgreen** [comment]
apologies :)
