### ISSUE TITLE
Feature Request / Question

### ISSUE THREAD

**Issue by chhex** [jenkinsci/java-client-api#297]
Are there any plans to support the https://github.com/jenkinsci/pipeline-stage-view-plugin/tree/master/rest-api?

**Comment by khmarbaise** [comment]
There is already a PR#218 but it had conflicts etc. But feel free to create another PR...I highly appreciate that...

**Comment by chhex** [comment]
Great thanks. I appreciate, i ll give it a try at least. I m a newbie here  .... 
Do i understand the process correctly: I fork the project into my own account. Change from there. If i feel comfortable, i create a PR ? 
BTW greeat job the java-client-api, really helpful

**Comment by chhex** [comment]
I appreciate , i ll give it a try at least. BTW thanks for the great work
