### ISSUE TITLE
Maven build with modules

### ISSUE THREAD

**Issue by dawon** [jenkinsci/java-client-api#309]
Hello,

I have a job with several modules, is it possible to access details (such as whether the build of module was successful, unstable, failed, console log of module and test results)? I was unable to find methods to obtain such info. Even though api allows to get this information (/job/[jobName]/[build]/[module]/api/xml)
Only thing I found was getMavenModule and getModuleRecords which gets me only information from pom file.

Thank you very much for any advice

Jakub

**Comment by doterme** [comment]
build.details().getConsoleOutputText()

**Comment by dawon** [comment]
Hi, 

this one doesn't do what I need. However I have written few classes, which add better Module support, so I guess this issue can be closed. 

Thank you

Jakub

**Comment by khmarbaise** [comment]
What about making a pull request ?

**Comment by dawon** [comment]
Pull Request submitted. Hope I did it the right way since this is my first Pull Request (ever)...

**Comment by khmarbaise** [comment]
@dawon would you please so kind to squash your commits...and create a issue for this ...and reference it in the commit message like:
```
Fixed #XX
 o Supplemental explanations
```
This would help a lot...

**Comment by dawon** [comment]
@khmarbaise I squashed the commits and created issue for it, or at least I thought I did:

see https://github.com/dawon/java-client-api/commit/6512454c1d0dceaab4570139e9dcd656ac325b0a
