### ISSUE TITLE
Proposal: Change checked exceptions to runtime exceptions

### ISSUE THREAD

**Issue by alexsuter** [jenkinsci/java-client-api#323]
Most methods of `com.offbytwo.jenkins.JenkinsServer` throws an checked exception (`java.io.IOException`). This makes the API harder to use - especially with lambdas. 

From the caller's side I can't do anything about it. I suggest defining a specific `RuntimeException `that contains the real cause. In this way, the caller can decide whether to handle the exception or not.

**Comment by khmarbaise** [comment]
Sounds like a good idea...
