### ISSUE TITLE
Release of Version 0.3.8

### ISSUE THREAD

**Issue by devdev-dev** [jenkinsci/java-client-api#330]
When can we except the version 0.3.8 to be released?

Thanks for your work,
Hendrik

**Comment by aderouineau** [comment]
Indeed, the last Maven release dates from December 2016, and there've been many updates since.

**Comment by khmarbaise** [comment]
Yes you are right...it is time for a new release...I hope I can do that on Weekend....

**Comment by mivola** [comment]
That would be perfect: we're currently evaluating the usage of a client library for Jenkins and a few of the features & bugfixes in 0.3.8 are a must-have!

**Comment by aderouineau** [comment]
@khmarbaise Any update?

**Comment by khmarbaise** [comment]
So officially done a new release. 0.3.8...
