### ISSUE TITLE
Enhancement: add Fluent-API to relevant setters in the model classes

### ISSUE THREAD

**Issue by mivola** [jenkinsci/java-client-api#360]
The setters in the model classes (i.e. BaseModel, Build, Job etc) should follow the Fluent-API pattern and return the object itself instead of void to allow the client calls like "artifact.setJenkinsServer(server).setClient(client);"

**Comment by khmarbaise** [comment]
Please squash your commits into a single commit and fix the commit message like this:
```
Fixed #360 
 - Optional explanation
```
That will help to close the issue automatically if it's merged to master.

**Comment by mivola** [comment]
@khmarbaise tbh I'm not sure which is the best way to do the squash - can you give me a short explanation?

**Comment by mivola** [comment]
@khmarbaise as I couldnt find a way to squash the commits in a remote branch, I created a new branch and a new PR:  #380. As an alternative: couldnt you squash the commits of this PR when merging it into master?
