### ISSUE TITLE
this bug  still exist

### ISSUE THREAD

**Issue by hujiachun** [jenkinsci/java-client-api#384]
this bug  still exist
version 0.3.8

<img width="1458" alt="2019-01-07 2 57 15" src="https://user-images.githubusercontent.com/17762932/50753451-e6e50180-128c-11e9-97b7-9cb3b71756bf.png">

_Originally posted by @hujiachun in https://github.com/jenkinsci/java-client-api/issues/118#issuecomment-451839875_

**Comment by khmarbaise** [comment]
Both of them https://github.com/jenkinsci/java-client-api/blob/master/jenkins-client/src/main/java/com/offbytwo/jenkins/model/Build.java#L148 and https://github.com/jenkinsci/java-client-api/blob/master/jenkins-client/src/main/java/com/offbytwo/jenkins/model/Build.java#L171 have been removed.
