### ISSUE TITLE
问一个构建的问题

### ISSUE THREAD

**Issue by kct12345** [jenkinsci/java-client-api#417]
build() return QueueReference, but QueueReference only have a queueItem field
How do I get the number for this build?
How to judge whether the build is completed or not?

**Comment by khmarbaise** [comment]
Could you please write in english

**Comment by Giftedl-Jarvis** [comment]
I have the same problem.
```
new JenkinsServer(url, name, token).getJob(jobName).build();
```
build() return QueueReference, but QueueReference only have a queueItem field
How do I get the number for this build?
How to judge whether the build is completed or not?

**Comment by dhubbard-ic** [comment]
You need to get the Build from JenkinServer using the QueueItem

                Build build = jenkins.getBuild(queueItem);
    
BUT you may have to wait until the job has been processed from the Queue and allocated to build.

The following works for me - with two while loops 1) to wait until Job is dispatched from the Queue and 2) while the build processes.

I guess you could use these two checks from outside to periodically poll, but this was a trial exercise for me.

 ```
      try {
            JenkinsServer jenkins = new JenkinsServer(new URI("http://localhost:15080"), "user", "XXXXXXX");
            
            Map<String, Job> jobs = jenkins.getJobs();
            
            System.out.println("Jobs: ["+jobs.size()+"]");
            
            Job job = jobs.get("MyJob");
            if (job != null) {
                
                System.out.println("Job: Name["+job.getName()+"] Url["+job.getUrl()+"]");
                
                QueueReference queueRef = job.build(true);
                QueueItem queueItem = null;
                if (queueRef != null) {
                    
                    System.out.println("Job in queue");
                    do {
                        queueItem = jenkins.getQueueItem(queueRef);
                        Thread.sleep(1000L);
                        System.out.print(".");
                        System.out.flush();
                    } 
                    while (queueItem.getExecutable() == null);
                   
                    System.out.println("");
                    System.out.println("Build Ref: ["+queueItem.getExecutable().getNumber()+"]");

                    Build build = jenkins.getBuild(queueItem);
                    
                    while (build.details().isBuilding()) {                        
                        Thread.sleep(1000L);
                        System.out.print(".");
                    }

                    BuildWithDetails details = build.details();                    
                    BuildResult result = details.getResult();
                    
                    System.out.println("");
                    System.out.println("Built: status["+result.name()+"] duration["+details.getDuration()+"]");
                }
                
            }

```

As you can see 

                 ```
   BuildWithDetails details = build.details();                    
                    BuildResult result = details.getResult();
```

and BuildResult is an enum 

```
public enum BuildResult {
    FAILURE, UNSTABLE, REBUILDING, BUILDING, ABORTED, SUCCESS, UNKNOWN, NOT_BUILT, CANCELLED

```

**Comment by dhubbard-ic** [comment]
BTW - Google translate of original post in English

"When using java remote call, remote build, how to judge when the project is completed, want to get the log information after the build, but when building, this build has not been completed, the acquisition is always the last time, I want to ask everyone how to solve this problem, asynchronous operation or other means"

**Comment by dhubbard-ic** [comment]
... and since I posted this I found [this cookbook](https://github.com/jenkinsci/java-client-api/wiki/Cookbook) in the Wiki.

**Comment by kct12345** [comment]
I am a newbie, sorry, thank you for your reply, now I solved this problem, I am performing it asynchronously, here is my code, thank you for correcting me.
/**
     * 服务构建
     *
     * @param id
     * @return
     */
    @ApiOperation(value = "构建服务", notes = "构建服务")
    @ApiImplicitParam(name = "id", value = "服务构建id", required = true, dataType = "String", paramType = "path")
    @PostMapping(value = "/buildJenkins/{id}")
    public Result buildJenkins(@PathVariable String id) throws Exception {
        ServiceInfo serviceInfo = serviceInfoService.findById(id);
        String jobName = serviceInfo.getShortName();
        String result = "";
        JenkinsServer jenkins = new JenkinsServer(new URI(jenkinsConfig.getJenUrl()), jenkinsConfig.getUsername(), jenkinsConfig.getPasswordorToken());
        if (jenkins.isRunning()) {
            JobWithDetails job = jenkins.getJob(jobName);
            if (job != null) {
                job.build();
                buildNumber = job.getNextBuildNumber();
                result = "任务正在构建中，请稍等";
            } else {
                throw new ServiceCenterException(ResultEnum.JENKINS_NOJOB_ERROR);
            }
        } else {
            throw new ServiceCenterException(ResultEnum.JENKINS_RUN_ERROR);
        }
        return ResultUtil.success(result);
    }

    /**
     * 查看日志
     *
     * @return
     */
    @ApiOperation(value = "日志查看", notes = "根据id查看日志")
    @ApiImplicitParam(name = "id", value = "日志id", required = true, dataType = "String", paramType = "path")
    @PostMapping(value = "/buildLod/{id}")
    public R showLog(@PathVariable String id) {
        ServiceInfo serviceInfo = serviceInfoService.findById(id);
        boolean finished = isFinished(buildNumber, serviceInfo);
        if (finished == true) {
            return R.ok(null, serviceInfo.getJenkinslog());
        }
        return R.failed("任务还在构建中");
    }

    /**
     * 判断job是否执行完
     *
     * @param number
     * @param serviceInfo
     * @return
     */
    public boolean isFinished(int number, ServiceInfo serviceInfo) {
        String jobName = serviceInfo.getShortName();
        boolean isBuilding = false;
        if (number <= 0) {
            throw new IllegalArgumentException("jodId must greater than 0!");
        }
        try {
            JenkinsServer jenkins = new JenkinsServer(new URI(jenkinsConfig.getJenUrl()), jenkinsConfig.getUsername(), jenkinsConfig.getPasswordorToken());
            ;
            Map<String, Job> jobs = jenkins.getJobs();
            JobWithDetails job = jobs.get(jobName).details();
            Build buildByNumber = job.getBuildByNumber(number);
            if (null != buildByNumber) {
                BuildWithDetails details = buildByNumber.details();
                if (null != details) {
                    isBuilding = details.isBuilding();
                    serviceInfo.setJenkinslog(details.getConsoleOutputText());
                    serviceInfoService.update(serviceInfo);
                    BuildResult result = details.getResult();
                } else {
                    isBuilding = true;
                }
            } else {
                isBuilding = true;
            }

            return !isBuilding;
        } catch (Exception e) {
            e.printStackTrace();
        } finally {

        }
        return false;
    }

**Comment by dhubbard-ag** [comment]
Hi - I'm glad you got it working - perhaps you can close this issue?
