### ISSUE TITLE
Question concerning the project status

### ISSUE THREAD

**Issue by andregmoeller** [jenkinsci/java-client-api#455]
First off, I don’t want to criticize anyone! Instead I have to say „thanks for all the work that has gone into the java-client-api“. Looking at the project’s [insights / pulse](https://github.com/jenkinsci/java-client-api/pulse/monthly), you will see little activity. So, I am wondering what’s the current project status?

**Comment by khmarbaise** [comment]
I hope to have a little bit more time within the next weeks also I would like to do another release cause there had pent-up a number of fixes which are not yet released....

**Comment by andregmoeller** [comment]
Thank you for replying so quickly!
