### ISSUE TITLE
Extracting testng and jacoco reports from Jenkins

### ISSUE THREAD

**Issue by JasmeenKaur19** [jenkinsci/java-client-api#98]
Right now , there is no api to get testng reports from a maven build(The available mvnJob.getLastSuccessfulBuild().getTestReport() doesn't get tesng reports). There should be one to get this information , the URI looks like JENKINS_BASE_URI/testngreports/api/json. 

Also to add jacoco report api

**Comment by khmarbaise** [comment]
Can we handle only a single part in a issue...so please make a separate issue for jacoco...

**Comment by khmarbaise** [comment]
Done with PR#252
